<Project Sdk="Microsoft.NET.Sdk">

  <!--
      All project use a standard compilation configuration
      which can be found in the Directory.Build.props file
      in the root of this repository.  Only overwrite those
      properties here if needed
  -->
  <PropertyGroup>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>ShyFox.ParticleEngine.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
